// frontend-react/src/pages/Dashboard.jsx
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import {
  Package,
  Wallet,
  Siren,
  ShoppingCart,
  TrendingUp,
  Boxes,
} from "lucide-react";
import client from "../api/client";
import AnimatedCard, {
  cardVariants,
  containerVariants,
} from "../components/ui/AnimatedCard";
import MetricBadge from "../components/ui/MetricBadge";
import StatusBadge from "../components/ui/StatusBadge";
import StockLevelChart from "../components/charts/StockLevelChart";
import RegionDonut from "../components/charts/RegionDonut";
import { useAlerts } from "../hooks/useAlerts";

function Metric({ icon: Icon, label, value, prefix, decimals, accent }) {
  return (
    <AnimatedCard className="relative overflow-hidden">
      <div className={`absolute -right-6 -top-6 h-20 w-20 rounded-full ${accent} opacity-20 blur-2xl`} />
      <div className="flex items-center justify-between">
        <span className="text-sm text-slate-400">{label}</span>
        <Icon size={18} className="text-cyan" />
      </div>
      <div className="mt-3 text-3xl font-extrabold text-white">
        <MetricBadge value={value} prefix={prefix} decimals={decimals} />
      </div>
      <div className="mt-2 flex items-center gap-1 text-xs text-emerald">
        <TrendingUp size={14} /> live
      </div>
    </AnimatedCard>
  );
}

export default function Dashboard() {
  const [stats, setStats] = useState(null);
  const [levels, setLevels] = useState({ by_region: [], by_category: [] });
  const { alerts } = useAlerts();

  useEffect(() => {
    client.get("/analytics/dashboard").then((r) => setStats(r.data));
    client.get("/analytics/stock-levels").then((r) => setLevels(r.data));
  }, []);

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="visible">
      <motion.div variants={cardVariants} className="mb-6 flex items-center gap-3">
        <Boxes className="text-cyan" />
        <div>
          <h1 className="text-2xl font-bold text-white">Command Center</h1>
          <p className="text-sm text-slate-400">
            Real-time view across all regional partitions
          </p>
        </div>
      </motion.div>

      {/* Metric row */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <Metric icon={Package} label="Total Products" value={stats?.total_products || 0} accent="bg-cyan" />
        <Metric
          icon={Wallet}
          label="Stock Value"
          value={stats?.total_stock_value || 0}
          prefix="₹"
          decimals={0}
          accent="bg-violet"
        />
        <Metric icon={Siren} label="Active Alerts" value={stats?.active_alerts || 0} accent="bg-danger" />
        <Metric icon={ShoppingCart} label="Orders Today" value={stats?.orders_today || 0} accent="bg-emerald" />
      </div>

      {/* Charts row */}
      <div className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-3">
        <AnimatedCard className="lg:col-span-2" hover={false}>
          <h3 className="mb-4 font-semibold text-white">Stock Units by Region</h3>
          <StockLevelChart data={levels.by_region} />
        </AnimatedCard>
        <AnimatedCard hover={false}>
          <h3 className="mb-4 font-semibold text-white">Distribution by Region</h3>
          <RegionDonut data={levels.by_region} />
        </AnimatedCard>
      </div>

      {/* Alerts + category row */}
      <div className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-3">
        <AnimatedCard className="lg:col-span-2" hover={false}>
          <div className="mb-4 flex items-center justify-between">
            <h3 className="font-semibold text-white">Stock by Category</h3>
          </div>
          <RegionDonut data={levels.by_category} nameKey="category" />
        </AnimatedCard>

        <AnimatedCard hover={false}>
          <div className="mb-4 flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-danger animate-pulseDot" />
            <h3 className="font-semibold text-white">Live Low-Stock Feed</h3>
          </div>
          <div className="flex max-h-72 flex-col gap-2 overflow-y-auto pr-1">
            {alerts.length === 0 && (
              <p className="text-sm text-slate-500">No active alerts. All healthy ✨</p>
            )}
            {alerts.map((a, i) => (
              <motion.div
                key={a.id}
                initial={{ opacity: 0, x: 24 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.05 }}
                className="flex items-center justify-between rounded-xl border border-danger/20 bg-danger/5 px-3 py-2"
              >
                <div>
                  <div className="text-sm font-medium text-white">{a.product_name}</div>
                  <div className="text-[11px] text-slate-400">
                    {a.warehouse_region} · qty {a.current_quantity}/{a.threshold}
                  </div>
                </div>
                <StatusBadge status="CRITICAL" />
              </motion.div>
            ))}
          </div>
        </AnimatedCard>
      </div>
    </motion.div>
  );
}

// frontend/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AnalyticsService, DashboardStats, StockLevels } from '../../services/analytics.service';
import { AlertService, Alert } from '../../services/alert.service';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  stats: DashboardStats = {
    total_products: 0,
    total_stock_value: 0,
    active_alerts: 0,
    orders_today: 0
  };
  levels: StockLevels = {
    by_region: [],
    by_category: []
  };
  alerts: Alert[] = [];
  loading = true;

  constructor(
    private analyticsService: AnalyticsService,
    private alertService: AlertService
  ) {}

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.loading = true;
    forkJoin({
      stats: this.analyticsService.getStats(),
      levels: this.analyticsService.getStockLevels(),
      alerts: this.alertService.getAlerts()
    }).subscribe({
      next: (res) => {
        this.stats = res.stats;
        this.levels = res.levels;
        this.alerts = res.alerts.filter(a => a.status === 'UNRESOLVED');
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  formatCurrency(value: number): string {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(value);
  }

  getRegionProgressWidth(qty: number): string {
    const max = Math.max(...this.levels.by_region.map(r => r.total_quantity), 1);
    return `${(qty / max) * 100}%`;
  }

  getCategoryProgressWidth(qty: number): string {
    const max = Math.max(...this.levels.by_category.map(c => c.total_quantity), 1);
    return `${(qty / max) * 100}%`;
  }
}

<div *ngIf="!loading" class="animate-fadeIn">
  <!-- Title Header -->
  <div class="mb-6 flex items-center gap-3">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-cyan">
      <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6A2.25 2.25 0 0 1 6 3.75h2.25A2.25 2.25 0 0 1 10.5 6v2.25a2.25 2.25 0 0 1-2.25 2.25H6a2.25 2.25 0 0 1-2.25-2.25V6ZM3.75 15.75A2.25 2.25 0 0 1 6 13.5h2.25a2.25 2.25 0 0 1 2.25 2.25V18a2.25 2.25 0 0 1-2.25 2.25H6A2.25 2.25 0 0 1 3.75 18v-2.25ZM13.5 6a2.25 2.25 0 0 1 2.25-2.25H18A2.25 2.25 0 0 1 20.25 6v2.25A2.25 2.25 0 0 1 18 10.5h-2.25a2.25 2.25 0 0 1-2.25-2.25V6ZM13.5 15.75a2.25 2.25 0 0 1 2.25-2.25H18a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 18 20.25h-2.25A2.25 2.25 0 0 1 13.5 18v-2.25Z" />
    </svg>
    <div>
      <h1 class="text-2xl font-bold text-slate-900">Command Center</h1>
      <p class="text-sm text-slate-400">
        Real-time view across all regional partitions
      </p>
    </div>
  </div>

  <!-- Metric row -->
  <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
    <!-- Metric 1: Total Products -->
    <div class="glass relative overflow-hidden rounded-2xl p-5 shadow-glow hover:scale-[1.02] hover:-translate-y-1 hover:shadow-lg transition-all duration-300">
      <div class="absolute -right-6 -top-6 h-20 w-20 rounded-full bg-cyan opacity-20 blur-2xl"></div>
      <div class="flex items-center justify-between">
        <span class="text-sm text-slate-450">Total Products</span>
        <svg class="h-5 w-5 text-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-14L4 7m8 4v10M4 7v10l8 4" /></svg>
      </div>
      <div class="mt-3 text-3xl font-extrabold text-slate-900">
        {{ stats.total_products }}
      </div>
      <div class="mt-2 flex items-center gap-1 text-xs text-violet font-semibold">
        <span class="h-1.5 w-1.5 rounded-full bg-violet animate-pulseDot"></span> live
      </div>
    </div>

    <!-- Metric 2: Stock Value -->
    <div class="glass relative overflow-hidden rounded-2xl p-5 shadow-glow hover:scale-[1.02] hover:-translate-y-1 hover:shadow-lg transition-all duration-300">
      <div class="absolute -right-6 -top-6 h-20 w-20 rounded-full bg-violet opacity-20 blur-2xl"></div>
      <div class="flex items-center justify-between">
        <span class="text-sm text-slate-450">Stock Value</span>
        <svg class="h-5 w-5 text-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M12 16v1" /></svg>
      </div>
      <div class="mt-3 text-3xl font-extrabold text-slate-900">
        {{ formatCurrency(stats.total_stock_value) }}
      </div>
      <div class="mt-2 flex items-center gap-1 text-xs text-violet font-semibold">
        <span class="h-1.5 w-1.5 rounded-full bg-violet animate-pulseDot"></span> live
      </div>
    </div>

    <!-- Metric 3: Active Alerts -->
    <div class="glass relative overflow-hidden rounded-2xl p-5 shadow-glow hover:scale-[1.02] hover:-translate-y-1 hover:shadow-lg transition-all duration-300">
      <div class="absolute -right-6 -top-6 h-20 w-20 rounded-full bg-danger opacity-20 blur-2xl"></div>
      <div class="flex items-center justify-between">
        <span class="text-sm text-slate-450">Active Alerts</span>
        <svg class="h-5 w-5 text-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
      </div>
      <div class="mt-3 text-3xl font-extrabold text-slate-900" [ngClass]="{'text-danger': stats.active_alerts > 0}">
        {{ stats.active_alerts }}
      </div>
      <div class="mt-2 flex items-center gap-1 text-xs text-violet font-semibold">
        <span class="h-1.5 w-1.5 rounded-full bg-violet animate-pulseDot"></span> live
      </div>
    </div>

    <!-- Metric 4: Orders Today -->
    <div class="glass relative overflow-hidden rounded-2xl p-5 shadow-glow hover:scale-[1.02] hover:-translate-y-1 hover:shadow-lg transition-all duration-300">
      <div class="absolute -right-6 -top-6 h-20 w-20 rounded-full bg-emerald opacity-20 blur-2xl"></div>
      <div class="flex items-center justify-between">
        <span class="text-sm text-slate-450">Orders Today</span>
        <svg class="h-5 w-5 text-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
      </div>
      <div class="mt-3 text-3xl font-extrabold text-slate-900">
        {{ stats.orders_today }}
      </div>
      <div class="mt-2 flex items-center gap-1 text-xs text-violet font-semibold">
        <span class="h-1.5 w-1.5 rounded-full bg-violet animate-pulseDot"></span> live
      </div>
    </div>
  </div>

  <!-- Regional Stock Level Charts -->
  <div class="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
    <!-- Regional levels -->
    <div class="glass rounded-2xl p-5 lg:col-span-2">
      <h3 class="mb-4 font-semibold text-slate-900">Stock Units by Region</h3>
      <div class="space-y-4">
        @for (region of levels.by_region; track region.region) {
          <div>
            <div class="mb-1 flex items-center justify-between text-xs text-slate-500 font-semibold">
              <span class="text-slate-800 font-semibold">{{ region.region }}</span>
              <span>{{ region.total_quantity }} units · {{ region.product_count }} types</span>
            </div>
            <div class="h-3 w-full rounded bg-slate-100 overflow-hidden">
              <div
                class="h-full rounded bg-gradient-to-r from-cyan to-violet shadow-glow transition-all duration-500"
                [style.width]="getRegionProgressWidth(region.total_quantity)"
              ></div>
            </div>
          </div>
        }
        @if (levels.by_region.length === 0) {
          <p class="text-center text-sm text-slate-500 py-6">No regional stock data found.</p>
        }
      </div>
    </div>

    <!-- Live alerts list -->
    <div class="glass rounded-2xl p-5">
      <div class="mb-4 flex items-center gap-2">
        <span class="h-2 w-2 rounded-full bg-danger animate-pulseDot"></span>
        <h3 class="font-semibold text-slate-900">Live Low-Stock Feed</h3>
      </div>
      <div class="flex max-h-72 flex-col gap-2 overflow-y-auto pr-1">
        @for (alert of alerts; track alert.id) {
          <div class="flex items-center justify-between rounded-xl border border-danger/20 bg-danger/5 px-3 py-2">
            <div>
              <div class="text-sm font-medium text-slate-900">{{ alert.product_name }}</div>
              <div class="text-[11px] text-slate-500">
                {{ alert.warehouse_region }} · qty {{ alert.current_quantity }}/{{ alert.threshold }}
              </div>
            </div>
            <span class="rounded-md bg-danger/10 border border-danger/20 px-2 py-0.5 text-[9px] font-bold text-danger tracking-wider">
              CRITICAL
            </span>
          </div>
        }
        @if (alerts.length === 0) {
          <p class="text-sm text-slate-500 text-center py-10">No active alerts. All healthy ✨</p>
        }
      </div>
    </div>
  </div>

  <!-- Category levels -->
  <div class="mt-6 grid grid-cols-1 gap-6">
    <div class="glass rounded-2xl p-5">
      <h3 class="mb-4 font-semibold text-slate-900">Stock Distribution by Category</h3>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        @for (category of levels.by_category; track category.category) {
          <div>
            <div class="mb-1 flex items-center justify-between text-xs text-slate-500 font-semibold">
              <span class="text-slate-800 font-semibold">{{ category.category }}</span>
              <span>{{ category.total_quantity }} units · {{ category.product_count }} types</span>
            </div>
            <div class="h-2.5 w-full rounded bg-slate-100 overflow-hidden">
              <div
                class="h-full rounded bg-gradient-to-r from-cyan to-emerald shadow-glow transition-all duration-500"
                [style.width]="getCategoryProgressWidth(category.total_quantity)"
              ></div>
            </div>
          </div>
        }
        @if (levels.by_category.length === 0) {
          <p class="col-span-2 text-center text-sm text-slate-500 py-6">No category data found.</p>
        }
      </div>
    </div>
  </div>
</div>

<!-- Loading spinner -->
<div *ngIf="loading" class="flex items-center justify-center py-20">
  <div class="h-8 w-8 animate-spin rounded-full border-4 border-cyan/20 border-t-cyan"></div>
</div>
