// frontend/src/pages/Products.jsx
import { useEffect, useState, useCallback } from "react";
import { motion } from "framer-motion";
import { Package, Plus, Pencil, Trash2, Search } from "lucide-react";
import toast from "react-hot-toast";
import client from "../api/client";
import PageHeader from "../components/ui/PageHeader";
import Modal from "../components/ui/Modal";
import ConfirmDialog from "../components/ui/ConfirmDialog";
import { containerVariants, cardVariants } from "../components/ui/AnimatedCard";

const EMPTY = {
  sku: "",
  name: "",
  category: "Electronics",
  unit_price: "",
  supplier_id: "",
  low_stock_threshold: 10,
};
const CATEGORIES = ["Electronics", "Apparel", "Food & Beverage", "Automotive", "Pharmaceuticals"];

export default function Products() {
  const [products, setProducts] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [query, setQuery] = useState("");
  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState(EMPTY);
  const [deleteId, setDeleteId] = useState(null);
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    const [p, s] = await Promise.all([
      client.get("/products"),
      client.get("/suppliers"),
    ]);
    setProducts(p.data);
    setSuppliers(s.data);
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  function openCreate() {
    setEditing(null);
    setForm(EMPTY);
    setModalOpen(true);
  }

  function openEdit(p) {
    setEditing(p);
    setForm({
      sku: p.sku,
      name: p.name,
      category: p.category || "Electronics",
      unit_price: p.unit_price,
      supplier_id: p.supplier_id || "",
      low_stock_threshold: p.low_stock_threshold,
    });
    setModalOpen(true);
  }

  async function save(e) {
    e.preventDefault();
    setSaving(true);
    const payload = {
      ...form,
      unit_price: parseFloat(form.unit_price),
      low_stock_threshold: parseInt(form.low_stock_threshold, 10),
      supplier_id: form.supplier_id ? parseInt(form.supplier_id, 10) : null,
    };
    try {
      if (editing) {
        await client.put(`/products/${editing.id}`, payload);
        toast.success("Product updated");
      } else {
        await client.post("/products", payload);
        toast.success("Product created");
      }
      setModalOpen(false);
      load();
    } catch {
      /* toasted */
    } finally {
      setSaving(false);
    }
  }

  async function remove() {
    try {
      await client.delete(`/products/${deleteId}`);
      toast.success("Product deleted");
      load();
    } catch {
      /* toasted */
    }
  }

  const filtered = products.filter((p) =>
    `${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(query.toLowerCase())
  );

  return (
    <div>
      <PageHeader
        title="Products"
        subtitle={`${products.length} SKUs in catalog`}
        icon={Package}
        action={
          <button
            onClick={openCreate}
            className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet px-4 py-2.5 text-sm font-semibold text-white shadow-glow"
          >
            <Plus size={18} /> Add Product
          </button>
        }
      />

      <div className="mb-4 flex items-center gap-2">
        <div className="relative flex-1" style={{ maxWidth: 360 }}>
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" />
          <input
            placeholder="Search products…"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="!pl-9"
          />
        </div>
      </div>

      <div className="glass overflow-hidden rounded-2xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-white/10 text-xs uppercase text-slate-400">
              <tr>
                <th className="px-4 py-3">SKU</th>
                <th className="px-4 py-3">Name</th>
                <th className="px-4 py-3">Category</th>
                <th className="px-4 py-3">Supplier</th>
                <th className="px-4 py-3 text-right">Price</th>
                <th className="px-4 py-3 text-right">Threshold</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <motion.tbody variants={containerVariants} initial="hidden" animate="visible">
              {filtered.map((p) => (
                <motion.tr
                  key={p.id}
                  variants={cardVariants}
                  className="border-b border-white/5 hover:bg-white/5"
                >
                  <td className="px-4 py-3 font-mono text-xs text-cyan">{p.sku}</td>
                  <td className="px-4 py-3 font-medium text-white">{p.name}</td>
                  <td className="px-4 py-3 text-slate-300">{p.category}</td>
                  <td className="px-4 py-3 text-slate-400">{p.supplier_name || "—"}</td>
                  <td className="px-4 py-3 text-right text-slate-200">
                    ₹{Number(p.unit_price).toLocaleString("en-IN")}
                  </td>
                  <td className="px-4 py-3 text-right text-slate-400">{p.low_stock_threshold}</td>
                  <td className="px-4 py-3">
                    <div className="flex justify-end gap-1">
                      <button
                        onClick={() => openEdit(p)}
                        className="rounded-lg p-2 text-slate-400 hover:bg-cyan/10 hover:text-cyan"
                      >
                        <Pencil size={16} />
                      </button>
                      <button
                        onClick={() => setDeleteId(p.id)}
                        className="rounded-lg p-2 text-slate-400 hover:bg-danger/10 hover:text-danger"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </td>
                </motion.tr>
              ))}
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-4 py-10 text-center text-slate-500">
                    No products found.
                  </td>
                </tr>
              )}
            </motion.tbody>
          </table>
        </div>
      </div>

      <Modal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        title={editing ? "Edit Product" : "Add Product"}
      >
        <form onSubmit={save} className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label>SKU</label>
              <input
                required
                value={form.sku}
                onChange={(e) => setForm({ ...form, sku: e.target.value })}
              />
            </div>
            <div>
              <label>Category</label>
              <select
                value={form.category}
                onChange={(e) => setForm({ ...form, category: e.target.value })}
              >
                {CATEGORIES.map((c) => (
                  <option key={c}>{c}</option>
                ))}
              </select>
            </div>
          </div>
          <div>
            <label>Name</label>
            <input
              required
              value={form.name}
              onChange={(e) => setForm({ ...form, name: e.target.value })}
            />
          </div>
          <div className="grid grid-cols-3 gap-3">
            <div>
              <label>Unit Price (₹)</label>
              <input
                required
                type="number"
                step="0.01"
                min="0"
                value={form.unit_price}
                onChange={(e) => setForm({ ...form, unit_price: e.target.value })}
              />
            </div>
            <div>
              <label>Threshold</label>
              <input
                type="number"
                min="0"
                value={form.low_stock_threshold}
                onChange={(e) => setForm({ ...form, low_stock_threshold: e.target.value })}
              />
            </div>
            <div>
              <label>Supplier</label>
              <select
                value={form.supplier_id}
                onChange={(e) => setForm({ ...form, supplier_id: e.target.value })}
              >
                <option value="">— None —</option>
                {suppliers.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.name}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={() => setModalOpen(false)}
              className="rounded-lg border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5"
            >
              Cancel
            </button>
            <button
              disabled={saving}
              className="rounded-lg bg-gradient-to-r from-cyan to-violet px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"
            >
              {saving ? "Saving…" : editing ? "Save changes" : "Create"}
            </button>
          </div>
        </form>
      </Modal>

      <ConfirmDialog
        open={deleteId != null}
        onClose={() => setDeleteId(null)}
        onConfirm={remove}
        message="Delete this product? Its inventory and alerts will also be removed."
      />
    </div>
  );
}

// frontend/src/app/pages/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ProductService, Product } from '../../services/product.service';
import { SupplierService, Supplier } from '../../services/supplier.service';
import { ToastService } from '../../services/toast.service';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.css']
})
export class ProductsComponent implements OnInit {
  products: Product[] = [];
  suppliers: Supplier[] = [];
  query = '';
  loading = true;

  // Modal States
  modalOpen = false;
  editing: Product | null = null;
  saving = false;

  // Form State
  form: Product = {
    sku: '',
    name: '',
    category: 'Electronics',
    unit_price: 0,
    supplier_id: null,
    low_stock_threshold: 10
  };

  // Delete State
  deleteId: number | null = null;

  categories = ["Electronics", "Apparel", "Food & Beverage", "Automotive", "Pharmaceuticals"];

  constructor(
    private productService: ProductService,
    private supplierService: SupplierService,
    private toast: ToastService
  ) {}

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.loading = true;
    forkJoin({
      products: this.productService.getProducts(),
      suppliers: this.supplierService.getSuppliers()
    }).subscribe({
      next: (res) => {
        this.products = res.products;
        this.suppliers = res.suppliers;
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  getFilteredProducts(): Product[] {
    if (!this.query.trim()) return this.products;
    const q = this.query.toLowerCase();
    return this.products.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
    );
  }

  openCreate(): void {
    this.editing = null;
    this.form = {
      sku: '',
      name: '',
      category: 'Electronics',
      unit_price: 0,
      supplier_id: this.suppliers.length > 0 ? (this.suppliers[0].id || null) : null,
      low_stock_threshold: 10
    };
    this.modalOpen = true;
  }

  openEdit(p: Product): void {
    this.editing = p;
    this.form = {
      sku: p.sku,
      name: p.name,
      category: p.category || 'Electronics',
      unit_price: p.unit_price,
      supplier_id: p.supplier_id || null,
      low_stock_threshold: p.low_stock_threshold
    };
    this.modalOpen = true;
  }

  saveProduct(event: Event): void {
    event.preventDefault();
    if (!this.form.sku || !this.form.name || this.form.unit_price <= 0) {
      this.toast.error('Please fill in all required fields');
      return;
    }

    this.saving = true;
    const payload: Product = {
      ...this.form,
      unit_price: Number(this.form.unit_price),
      low_stock_threshold: Number(this.form.low_stock_threshold),
      supplier_id: this.form.supplier_id ? Number(this.form.supplier_id) : null
    };

    if (this.editing && this.editing.id) {
      this.productService.updateProduct(this.editing.id, payload).subscribe({
        next: () => {
          this.toast.success('Product updated successfully');
          this.modalOpen = false;
          this.loadData();
          this.saving = false;
        },
        error: () => {
          this.saving = false;
        }
      });
    } else {
      this.productService.createProduct(payload).subscribe({
        next: () => {
          this.toast.success('Product created successfully');
          this.modalOpen = false;
          this.loadData();
          this.saving = false;
        },
        error: () => {
          this.saving = false;
        }
      });
    }
  }

  confirmDelete(id: number): void {
    this.deleteId = id;
  }

  cancelDelete(): void {
    this.deleteId = null;
  }

  deleteProduct(): void {
    if (this.deleteId === null) return;
    this.productService.deleteProduct(this.deleteId).subscribe({
      next: () => {
        this.toast.success('Product deleted successfully');
        this.deleteId = null;
        this.loadData();
      }
    });
  }
}

<div class="animate-fadeIn">
  <!-- Page Header -->
  <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
    <div>
      <h1 class="text-2xl font-bold text-slate-900 flex items-center gap-2">
        <svg class="w-6 h-6 text-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-14L4 7m8 4v10M4 7v10l8 4" /></svg>
        Products
      </h1>
      <p class="text-sm text-slate-500">{{ products.length }} SKUs in catalog</p>
    </div>
    <button
      (click)="openCreate()"
      class="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet px-4 py-2.5 text-sm font-semibold text-white shadow-glow hover:opacity-90 transition duration-300"
    >
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
      </svg>
      Add Product
    </button>
  </div>

  <!-- Search Bar -->
  <div class="mb-4 flex items-center gap-2">
    <div class="relative flex-1" style="max-width: 360px;">
      <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
      <input
        placeholder="Search products…"
        [(ngModel)]="query"
        class="!pl-9"
      />
    </div>
  </div>

  <!-- Products Grid Table -->
  <div class="glass overflow-hidden rounded-2xl">
    <div class="overflow-x-auto">
      <table class="w-full text-left text-sm">
        <thead class="border-b border-slate-200 text-xs uppercase text-slate-500">
          <tr>
            <th class="px-4 py-3">SKU</th>
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Category</th>
            <th class="px-4 py-3">Supplier</th>
            <th class="px-4 py-3 text-right">Price</th>
            <th class="px-4 py-3 text-right">Threshold</th>
            <th class="px-4 py-3 text-right">Actions</th>
          </tr>
        </thead>
        <tbody>
          @for (p of getFilteredProducts(); track p.id) {
            <tr class="border-b border-slate-100 hover:bg-slate-50 transition duration-150">
              <td class="px-4 py-3 font-mono text-xs text-cyan font-bold">{{ p.sku }}</td>
              <td class="px-4 py-3 font-semibold text-slate-900">{{ p.name }}</td>
              <td class="px-4 py-3 text-slate-600">{{ p.category }}</td>
              <td class="px-4 py-3 text-slate-500">{{ p.supplier_name || '—' }}</td>
              <td class="px-4 py-3 text-right text-slate-800 font-semibold">
                ₹{{ p.unit_price | number:'1.0-0' }}
              </td>
              <td class="px-4 py-3 text-right text-slate-600">{{ p.low_stock_threshold }}</td>
              <td class="px-4 py-3">
                <div class="flex justify-end gap-1">
                  <button
                    (click)="openEdit(p)"
                    class="rounded-lg p-2 text-slate-500 hover:bg-cyan/10 hover:text-cyan transition duration-150"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.83 18.75a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                    </svg>
                  </button>
                  <button
                    (click)="confirmDelete(p.id!)"
                    class="rounded-lg p-2 text-slate-500 hover:bg-danger/10 hover:text-danger transition duration-150"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                    </svg>
                  </button>
                </div>
              </td>
            </tr>
          }
          @if (getFilteredProducts().length === 0 && !loading) {
            <tr>
              <td colSpan="7" class="px-4 py-10 text-center text-slate-500 font-medium">
                No products found.
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  </div>

  <!-- Loading indicator -->
  <div *ngIf="loading" class="flex items-center justify-center py-20">
    <div class="h-8 w-8 animate-spin rounded-full border-4 border-cyan/20 border-t-cyan"></div>
  </div>

  <!-- Add/Edit Modal Overlay -->
  <div *ngIf="modalOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
    <div class="glass w-full max-w-lg rounded-3xl p-6 shadow-2xl relative">
      <h3 class="text-xl font-bold text-slate-900 mb-4">
        {{ editing ? 'Edit Product' : 'Add Product' }}
      </h3>
      <button (click)="modalOpen = false" class="absolute top-4 right-4 text-slate-500 hover:text-slate-950 text-xl">&times;</button>
      
      <form (submit)="saveProduct($event)" class="space-y-4">
        <div class="grid grid-cols-2 gap-3">
          <div>
            <label>SKU</label>
            <input required placeholder="e.g. ELEC-LAP01" [(ngModel)]="form.sku" name="sku" />
          </div>
          <div>
            <label>Name</label>
            <input required placeholder="e.g. Laptop Pro" [(ngModel)]="form.name" name="name" />
          </div>
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div>
            <label>Category</label>
            <select [(ngModel)]="form.category" name="category">
              @for (cat of categories; track cat) {
                <option [value]="cat">{{ cat }}</option>
              }
            </select>
          </div>
          <div>
            <label>Supplier</label>
            <select [(ngModel)]="form.supplier_id" name="supplier_id">
              <option [ngValue]="null">— None —</option>
              @for (s of suppliers; track s.id) {
                <option [value]="s.id">{{ s.name }}</option>
              }
            </select>
          </div>
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div>
            <label>Unit Price (₹)</label>
            <input type="number" required placeholder="0.00" [(ngModel)]="form.unit_price" name="unit_price" />
          </div>
          <div>
            <label>Low-Stock Threshold</label>
            <input type="number" required placeholder="10" [(ngModel)]="form.low_stock_threshold" name="low_stock_threshold" />
          </div>
        </div>

        <div class="flex justify-end gap-2 pt-4">
          <button
            type="button"
            (click)="modalOpen = false"
            class="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition duration-150"
          >
            Cancel
          </button>
          <button
            type="submit"
            [disabled]="saving"
            class="px-4 py-2 text-sm font-semibold bg-gradient-to-r from-cyan to-violet text-white rounded-xl shadow-glow disabled:opacity-60 transition duration-150"
          >
            {{ saving ? 'Saving…' : 'Save Product' }}
          </button>
        </div>
      </form>
    </div>
  </div>

  <!-- Delete Confirmation Modal -->
  <div *ngIf="deleteId !== null" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
    <div class="glass w-full max-w-sm rounded-3xl p-6 shadow-2xl">
      <h3 class="text-lg font-bold text-slate-900 mb-2">Delete Product?</h3>
      <p class="text-sm text-slate-600 mb-6">
        Are you sure you want to delete this product? This action cannot be undone.
      </p>
      <div class="flex justify-end gap-2">
        <button
          (click)="cancelDelete()"
          class="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition duration-150"
        >
          Cancel
        </button>
        <button
          (click)="deleteProduct()"
          class="px-4 py-2 text-sm font-semibold bg-danger text-white rounded-xl hover:bg-danger/80 transition duration-150"
        >
          Delete
        </button>
      </div>
    </div>
  </div>
</div>
