// frontend-react/src/pages/Warehouses.jsx
import { useEffect, useState, useCallback } from "react";
import { motion } from "framer-motion";
import { Factory, Plus, Pencil, Trash2, MapPin, Database } from "lucide-react";
import toast from "react-hot-toast";
import client from "../api/client";
import PageHeader from "../components/ui/PageHeader";
import Modal from "../components/ui/Modal";
import ConfirmDialog from "../components/ui/ConfirmDialog";
import { containerVariants, cardVariants } from "../components/ui/AnimatedCard";

const REGIONS = ["NORTH", "SOUTH", "EAST", "WEST", "CENTRAL"];
const EMPTY = { name: "", region: "NORTH", location: "", capacity: 10000 };

const REGION_COLOR = {
  NORTH: "from-cyan/20 to-cyan/5 text-cyan",
  SOUTH: "from-violet/20 to-violet/5 text-violet",
  EAST: "from-emerald/20 to-emerald/5 text-emerald",
  WEST: "from-amber/20 to-amber/5 text-amber",
  CENTRAL: "from-danger/20 to-danger/5 text-danger",
};

export default function Warehouses() {
  const [warehouses, setWarehouses] = useState([]);
  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState(EMPTY);
  const [deleteId, setDeleteId] = useState(null);
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    const { data } = await client.get("/warehouses");
    setWarehouses(data);
  }, []);
  useEffect(() => {
    load();
  }, [load]);

  function openCreate() {
    setEditing(null);
    setForm(EMPTY);
    setModalOpen(true);
  }
  function openEdit(w) {
    setEditing(w);
    setForm({ name: w.name, region: w.region, location: w.location || "", capacity: w.capacity });
    setModalOpen(true);
  }

  async function save(e) {
    e.preventDefault();
    setSaving(true);
    try {
      if (editing) {
        // region is the partition key — not editable in place
        const { region, ...rest } = form;
        await client.put(`/warehouses/${editing.id}`, { ...rest, capacity: parseInt(form.capacity, 10) });
        toast.success("Warehouse updated");
      } else {
        await client.post("/warehouses", { ...form, capacity: parseInt(form.capacity, 10) });
        toast.success("Warehouse created");
      }
      setModalOpen(false);
      load();
    } catch {
      /* toasted */
    } finally {
      setSaving(false);
    }
  }

  async function remove() {
    try {
      await client.delete(`/warehouses/${deleteId}`);
      toast.success("Warehouse deleted");
      load();
    } catch {
      /* toasted */
    }
  }

  return (
    <div>
      <PageHeader
        title="Warehouses"
        subtitle="LIST-partitioned by region — each card shows its physical partition"
        icon={Factory}
        action={
          <button
            onClick={openCreate}
            className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet px-4 py-2.5 text-sm font-semibold text-white shadow-glow"
          >
            <Plus size={18} /> Add Warehouse
          </button>
        }
      />

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3"
      >
        {warehouses.map((w) => (
          <motion.div
            key={`${w.id}-${w.region}`}
            variants={cardVariants}
            whileHover={{ y: -4 }}
            className={`glass relative overflow-hidden rounded-2xl bg-gradient-to-br p-5 ${REGION_COLOR[w.region] || ""}`}
          >
            <div className="flex items-start justify-between">
              <div>
                <h3 className="font-semibold text-white">{w.name}</h3>
                <span className="text-xs font-bold uppercase tracking-wider">{w.region}</span>
              </div>
              <span className="rounded-lg bg-white/10 px-2 py-1 text-[10px] font-semibold text-white">
                #{w.id}
              </span>
            </div>
            <div className="mt-3 flex items-center gap-2 text-sm text-slate-300">
              <MapPin size={14} /> {w.location || "—"}
            </div>
            <div className="mt-2 text-sm text-slate-400">
              Capacity: {Number(w.capacity).toLocaleString("en-IN")} units
            </div>
            <div className="mt-3 flex items-center gap-1.5 rounded-lg border border-white/10 bg-black/30 px-2 py-1 text-[11px] font-mono text-slate-300">
              <Database size={12} /> partition: {w.partition}
            </div>
            <div className="mt-3 flex justify-end gap-1">
              <button
                onClick={() => openEdit(w)}
                className="rounded-lg p-2 text-slate-300 hover:bg-white/10"
              >
                <Pencil size={16} />
              </button>
              <button
                onClick={() => setDeleteId(w.id)}
                className="rounded-lg p-2 text-slate-300 hover:bg-danger/20 hover:text-danger"
              >
                <Trash2 size={16} />
              </button>
            </div>
          </motion.div>
        ))}
      </motion.div>

      <Modal
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        title={editing ? "Edit Warehouse" : "Add Warehouse"}
      >
        <form onSubmit={save} className="space-y-3">
          <div>
            <label>Name</label>
            <input
              required
              value={form.name}
              onChange={(e) => setForm({ ...form, name: e.target.value })}
            />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label>Region {editing && "(fixed — partition key)"}</label>
              <select
                disabled={!!editing}
                value={form.region}
                onChange={(e) => setForm({ ...form, region: e.target.value })}
              >
                {REGIONS.map((r) => (
                  <option key={r}>{r}</option>
                ))}
              </select>
            </div>
            <div>
              <label>Capacity</label>
              <input
                type="number"
                min="0"
                value={form.capacity}
                onChange={(e) => setForm({ ...form, capacity: e.target.value })}
              />
            </div>
          </div>
          <div>
            <label>Location</label>
            <input
              value={form.location}
              onChange={(e) => setForm({ ...form, location: e.target.value })}
            />
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={() => setModalOpen(false)}
              className="rounded-lg border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5"
            >
              Cancel
            </button>
            <button
              disabled={saving}
              className="rounded-lg bg-gradient-to-r from-cyan to-violet px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"
            >
              {saving ? "Saving…" : editing ? "Save" : "Create"}
            </button>
          </div>
        </form>
      </Modal>

      <ConfirmDialog
        open={deleteId != null}
        onClose={() => setDeleteId(null)}
        onConfirm={remove}
        message="Delete this warehouse? Make sure no inventory references it."
      />
    </div>
  );
}

// frontend/src/app/pages/warehouses/warehouses.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { WarehouseService, Warehouse } from '../../services/warehouse.service';
import { ToastService } from '../../services/toast.service';

@Component({
  selector: 'app-warehouses',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './warehouses.component.html',
  styleUrls: ['./warehouses.component.css']
})
export class WarehousesComponent implements OnInit {
  warehouses: Warehouse[] = [];
  query = '';
  loading = true;

  // Modal States
  modalOpen = false;
  editing: Warehouse | null = null;
  saving = false;

  // Form State
  form: Warehouse = {
    name: '',
    region: 'NORTH',
    capacity: 1000
  };

  // Delete State
  deleteId: number | null = null;

  regions = ['NORTH', 'SOUTH', 'EAST', 'WEST', 'CENTRAL'];

  constructor(
    private warehouseService: WarehouseService,
    private toast: ToastService
  ) {}

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.loading = true;
    this.warehouseService.getWarehouses().subscribe({
      next: (res) => {
        this.warehouses = res;
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  getFilteredWarehouses(): Warehouse[] {
    if (!this.query.trim()) return this.warehouses;
    const q = this.query.toLowerCase();
    return this.warehouses.filter(w =>
      w.name.toLowerCase().includes(q) ||
      w.region.toLowerCase().includes(q)
    );
  }

  openCreate(): void {
    this.editing = null;
    this.form = {
      name: '',
      region: 'NORTH',
      capacity: 1000
    };
    this.modalOpen = true;
  }

  openEdit(w: Warehouse): void {
    this.editing = w;
    this.form = {
      name: w.name,
      region: w.region || 'NORTH',
      capacity: w.capacity
    };
    this.modalOpen = true;
  }

  saveWarehouse(event: Event): void {
    event.preventDefault();
    if (!this.form.name || !this.form.region || this.form.capacity <= 0) {
      this.toast.error('Please fill in all required fields');
      return;
    }

    this.saving = true;
    const payload: Warehouse = {
      ...this.form,
      capacity: Number(this.form.capacity)
    };

    if (this.editing && this.editing.id) {
      this.warehouseService.updateWarehouse(this.editing.id, payload).subscribe({
        next: () => {
          this.toast.success('Warehouse updated successfully');
          this.modalOpen = false;
          this.loadData();
          this.saving = false;
        },
        error: () => {
          this.saving = false;
        }
      });
    } else {
      this.warehouseService.createWarehouse(payload).subscribe({
        next: () => {
          this.toast.success('Warehouse created successfully');
          this.modalOpen = false;
          this.loadData();
          this.saving = false;
        },
        error: () => {
          this.saving = false;
        }
      });
    }
  }

  confirmDelete(id: number): void {
    this.deleteId = id;
  }

  cancelDelete(): void {
    this.deleteId = null;
  }

  deleteWarehouse(): void {
    if (this.deleteId === null) return;
    this.warehouseService.deleteWarehouse(this.deleteId).subscribe({
      next: () => {
        this.toast.success('Warehouse deleted successfully');
        this.deleteId = null;
        this.loadData();
      }
    });
  }
}

<div class="animate-fadeIn">
  <!-- Page Header -->
  <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
    <div>
      <h1 class="text-2xl font-bold text-slate-900 flex items-center gap-2">
        <svg class="w-6 h-6 text-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>
        Warehouses (Servers)
      </h1>
      <p class="text-sm text-slate-500">{{ warehouses.length }} regional partitions</p>
    </div>
    <button
      (click)="openCreate()"
      class="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet px-4 py-2.5 text-sm font-semibold text-white shadow-glow hover:opacity-90 transition duration-300"
    >
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
      </svg>
      Add Warehouse
    </button>
  </div>

  <!-- Search Bar -->
  <div class="mb-4 flex items-center gap-2">
    <div class="relative flex-1" style="max-width: 360px;">
      <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
      <input
        placeholder="Search warehouses…"
        [(ngModel)]="query"
        class="!pl-9"
      />
    </div>
  </div>

  <!-- Warehouses Table -->
  <div class="glass overflow-hidden rounded-2xl">
    <div class="overflow-x-auto">
      <table class="w-full text-left text-sm">
        <thead class="border-b border-slate-200 text-xs uppercase text-slate-500">
          <tr>
            <th class="px-4 py-3">ID</th>
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Region</th>
            <th class="px-4 py-3 text-right">Capacity (units)</th>
            <th class="px-4 py-3 text-right">Actions</th>
          </tr>
        </thead>
        <tbody>
          @for (w of getFilteredWarehouses(); track w.id) {
            <tr class="border-b border-slate-100 hover:bg-slate-50 transition duration-150">
              <td class="px-4 py-3 text-slate-500">#{{ w.id }}</td>
              <td class="px-4 py-3 font-semibold text-slate-900">{{ w.name }}</td>
              <td class="px-4 py-3">
                <span class="rounded bg-violet/10 border border-violet/20 px-2 py-0.5 text-xs text-violet font-bold">
                  {{ w.region }}
                </span>
              </td>
              <td class="px-4 py-3 text-right text-slate-800 font-semibold">
                {{ w.capacity | number }}
              </td>
              <td class="px-4 py-3">
                <div class="flex justify-end gap-1">
                  <button
                    (click)="openEdit(w)"
                    class="rounded-lg p-2 text-slate-500 hover:bg-cyan/10 hover:text-cyan transition duration-150"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.83 18.75a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                    </svg>
                  </button>
                  <button
                    (click)="confirmDelete(w.id!)"
                    class="rounded-lg p-2 text-slate-500 hover:bg-danger/10 hover:text-danger transition duration-150"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                    </svg>
                  </button>
                </div>
              </td>
            </tr>
          }
          @if (getFilteredWarehouses().length === 0 && !loading) {
            <tr>
              <td colSpan="5" class="px-4 py-10 text-center text-slate-500 font-medium">
                No warehouses found.
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  </div>

  <!-- Loading indicator -->
  <div *ngIf="loading" class="flex items-center justify-center py-20">
    <div class="h-8 w-8 animate-spin rounded-full border-4 border-cyan/20 border-t-cyan"></div>
  </div>

  <!-- Add/Edit Modal Overlay -->
  <div *ngIf="modalOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
    <div class="glass w-full max-w-md rounded-3xl p-6 shadow-2xl relative">
      <h3 class="text-xl font-bold text-slate-900 mb-4">
        {{ editing ? 'Edit Warehouse' : 'Add Warehouse' }}
      </h3>
      <button (click)="modalOpen = false" class="absolute top-4 right-4 text-slate-500 hover:text-slate-950 text-xl">&times;</button>
      
      <form (submit)="saveWarehouse($event)" class="space-y-4">
        <div>
          <label>Warehouse Name</label>
          <input required placeholder="e.g. London Server" [(ngModel)]="form.name" name="name" />
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div>
            <label>Region Partition</label>
            <select [(ngModel)]="form.region" name="region">
              @for (r of regions; track r) {
                <option [value]="r">{{ r }}</option>
              }
            </select>
          </div>
          <div>
            <label>Capacity</label>
            <input type="number" required placeholder="1000" [(ngModel)]="form.capacity" name="capacity" />
          </div>
        </div>

        <div class="flex justify-end gap-2 pt-4">
          <button
            type="button"
            (click)="modalOpen = false"
            class="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition duration-150"
          >
            Cancel
          </button>
          <button
            type="submit"
            [disabled]="saving"
            class="px-4 py-2 text-sm font-semibold bg-gradient-to-r from-cyan to-violet text-white rounded-xl shadow-glow disabled:opacity-60 transition duration-150"
          >
            {{ saving ? 'Saving…' : 'Save Warehouse' }}
          </button>
        </div>
      </form>
    </div>
  </div>

  <!-- Delete Confirmation Modal -->
  <div *ngIf="deleteId !== null" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
    <div class="glass w-full max-w-sm rounded-3xl p-6 shadow-2xl">
      <h3 class="text-lg font-bold text-slate-900 mb-2">Delete Warehouse?</h3>
      <p class="text-sm text-slate-600 mb-6">
        Are you sure you want to delete this warehouse? This action cannot be undone.
      </p>
      <div class="flex justify-end gap-2">
        <button
          (click)="cancelDelete()"
          class="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition duration-150"
        >
          Cancel
        </button>
        <button
          (click)="deleteWarehouse()"
          class="px-4 py-2 text-sm font-semibold bg-danger text-white rounded-xl hover:bg-danger/80 transition duration-150"
        >
          Delete
        </button>
      </div>
    </div>
  </div>
</div>
