// frontend/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ToastService } from '../../services/toast.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;
  loading = false;

  constructor(
    private fb: FormBuilder,
    private auth: AuthService,
    private router: Router,
    private toast: ToastService
  ) {}

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      username: ['admin', [Validators.required]],
      password: ['admin123', [Validators.required]]
    });
  }

  get username() { return this.loginForm.get('username'); }
  get password() { return this.loginForm.get('password'); }

  onSubmit(event: Event): void {
    event.preventDefault();
    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      this.toast.error('Please fill in all required fields');
      return;
    }

    this.loading = true;
    const { username, password } = this.loginForm.value;
    this.auth.login(username, password).subscribe({
      next: () => {
        this.toast.success('Welcome to AIR 1');
        this.router.navigate(['/']);
      },
      error: () => {
        this.loading = false;
      },
      complete: () => {
        this.loading = false;
      }
    });
  }
}

<div class="flex min-h-screen items-center justify-center p-4">
  <div class="glass w-full max-w-md rounded-3xl p-8 shadow-glow-violet animate-fadeIn">
    <div class="mb-8 flex flex-col items-center text-center">
      <div class="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-black shadow-glow">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-7 h-7 text-white">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 13.5h3.86a2.25 2.25 0 0 1 2.008 1.24l.885 1.77a2.25 2.25 0 0 0 2.007 1.24h1.98a2.25 2.25 0 0 0 2.007-1.24l.885-1.77a2.25 2.25 0 0 1 2.007-1.24h3.86m-18 0h18" />
        </svg>
      </div>
      <h1 class="gradient-text text-3xl font-extrabold tracking-tight">AIR 1</h1>
      <p class="mt-1 text-sm text-slate-400">
        Intelligent Inventory &amp; Supply Chain Platform
      </p>
    </div>

    <form [formGroup]="loginForm" (submit)="onSubmit($event)" class="space-y-4">
      <div>
        <label>Username</label>
        <input formControlName="username" class="w-full"
               [ngClass]="{ 'border-danger/50 focus:border-danger': username?.invalid && username?.touched }" />
        @if (username?.invalid && username?.touched) {
          <small class="text-xs text-danger mt-1 block">Username is required.</small>
        }
      </div>
      <div>
        <label>Password</label>
        <input type="password" formControlName="password" class="w-full"
               [ngClass]="{ 'border-danger/50 focus:border-danger': password?.invalid && password?.touched }" />
        @if (password?.invalid && password?.touched) {
          <small class="text-xs text-danger mt-1 block">Password is required.</small>
        }
      </div>
      <button
        type="submit"
        [disabled]="loading"
        class="flex w-full items-center justify-center gap-2 rounded-xl bg-black py-3 font-semibold text-white shadow-glow disabled:opacity-60 hover:bg-slate-900 transition duration-300"
      >
        <svg *ngIf="!loading" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15M12 9l-3 3m0 0 3 3m-3-3h12.75" />
        </svg>
        <span>{{ loading ? 'Signing in…' : 'Sign in' }}</span>
      </button>
    </form>

    <p class="mt-6 text-center text-xs text-slate-500">
      Demo credentials: <span class="text-cyan">admin / admin123</span>
    </p>
  </div>
</div>

// frontend/src/pages/Login.jsx
import { useState } from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { Boxes, LogIn } from "lucide-react";
import { useAuthStore } from "../store/authStore";

export default function Login() {
  const navigate = useNavigate();
  const login = useAuthStore((s) => s.login);
  const [username, setUsername] = useState("admin");
  const [password, setPassword] = useState("admin123");
  const [loading, setLoading] = useState(false);

  async function submit(e) {
    e.preventDefault();
    setLoading(true);
    try {
      await login(username, password);
      toast.success("Welcome to TrackOS");
      navigate("/");
    } catch {
      /* interceptor toasts */
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, y: 24, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ duration: 0.5, ease: "easeOut" }}
        className="glass w-full max-w-md rounded-3xl p-8 shadow-glow-violet"
      >
        <div className="mb-8 flex flex-col items-center text-center">
          <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan to-violet shadow-glow">
            <Boxes size={28} className="text-white" />
          </div>
          <h1 className="gradient-text text-3xl font-extrabold">TRACKOS</h1>
          <p className="mt-1 text-sm text-slate-400">
            Intelligent Inventory &amp; Supply Chain Platform
          </p>
        </div>

        <form onSubmit={submit} className="space-y-4">
          <div>
            <label>Username</label>
            <input value={username} onChange={(e) => setUsername(e.target.value)} />
          </div>
          <div>
            <label>Password</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <motion.button
            whileTap={{ scale: 0.97 }}
            disabled={loading}
            className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet py-3 font-semibold text-white shadow-glow disabled:opacity-60"
          >
            <LogIn size={18} />
            {loading ? "Signing in…" : "Sign in"}
          </motion.button>
        </form>

        <p className="mt-6 text-center text-xs text-slate-500">
          Demo credentials: <span className="text-cyan">admin / admin123</span>
        </p>
      </motion.div>
    </div>
  );
}
