// frontend/src/app/pages/orders/orders.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { OrderService, Order } from '../../services/order.service';
import { ProductService, Product } from '../../services/product.service';
import { WarehouseService, Warehouse } from '../../services/warehouse.service';
import { ToastService } from '../../services/toast.service';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-orders',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './orders.component.html',
  styleUrls: ['./orders.component.css']
})
export class OrdersComponent implements OnInit {
  orders: Order[] = [];
  products: Product[] = [];
  warehouses: Warehouse[] = [];
  query = '';
  loading = true;

  // Modal State
  modalOpen = false;
  saving = false;

  // Form State
  form = {
    product_id: 0,
    warehouse_id: 0,
    quantity: 1,
    customer_name: ''
  };

  constructor(
    private orderService: OrderService,
    private productService: ProductService,
    private warehouseService: WarehouseService,
    private toast: ToastService
  ) {}

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.loading = true;
    forkJoin({
      orders: this.orderService.getOrders(),
      products: this.productService.getProducts(),
      warehouses: this.warehouseService.getWarehouses()
    }).subscribe({
      next: (res) => {
        this.orders = res.orders;
        this.products = res.products;
        this.warehouses = res.warehouses;
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  getFilteredOrders(): Order[] {
    if (!this.query.trim()) return this.orders;
    const q = this.query.toLowerCase();
    return this.orders.filter(o =>
      o.customer_name.toLowerCase().includes(q) ||
      (o.product_name || '').toLowerCase().includes(q) ||
      (o.status || '').toLowerCase().includes(q)
    );
  }

  openCreate(): void {
    if (this.products.length === 0 || this.warehouses.length === 0) {
      this.toast.error('Products and warehouses must exist first');
      return;
    }
    this.form = {
      product_id: this.products[0].id || 0,
      warehouse_id: this.warehouses[0].id || 0,
      quantity: 1,
      customer_name: ''
    };
    this.modalOpen = true;
  }

  saveOrder(event: Event): void {
    event.preventDefault();
    if (!this.form.customer_name || this.form.quantity <= 0) {
      this.toast.error('Please enter customer name and quantity');
      return;
    }

    this.saving = true;
    const payload = {
      product_id: Number(this.form.product_id),
      warehouse_id: Number(this.form.warehouse_id),
      quantity: Number(this.form.quantity),
      customer_name: this.form.customer_name
    };

    this.orderService.createOrder(payload).subscribe({
      next: () => {
        this.toast.success('Order placed successfully');
        this.modalOpen = false;
        this.loadData();
        this.saving = false;
      },
      error: () => {
        this.saving = false;
      }
    });
  }

  fulfillOrder(id: number): void {
    this.orderService.fulfillOrder(id).subscribe({
      next: () => {
        this.toast.success('Order fulfilled successfully! Inventory stock updated.');
        this.loadData();
      }
    });
  }

  deleteOrder(id: number): void {
    this.orderService.deleteOrder(id).subscribe({
      next: () => {
        this.toast.success('Order cancelled and deleted');
        this.loadData();
      }
    });
  }
}

<div class="animate-fadeIn">
  <!-- Page Header -->
  <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
    <div>
      <h1 class="text-2xl font-bold text-slate-900 flex items-center gap-2">
        <svg class="w-6 h-6 text-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
        Orders
      </h1>
      <p class="text-sm text-slate-500">{{ orders.length }} customer orders placed</p>
    </div>
    <button
      (click)="openCreate()"
      class="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet px-4 py-2.5 text-sm font-semibold text-white shadow-glow hover:opacity-90 transition duration-300"
    >
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
      </svg>
      Place Order
    </button>
  </div>

  <!-- Search Bar -->
  <div class="mb-4 flex items-center gap-2">
    <div class="relative flex-1" style="max-width: 360px;">
      <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
      <input
        placeholder="Search orders…"
        [(ngModel)]="query"
        class="!pl-9"
      />
    </div>
  </div>

  <!-- Orders Table -->
  <div class="glass overflow-hidden rounded-2xl">
    <div class="overflow-x-auto">
      <table class="w-full text-left text-sm">
        <thead class="border-b border-slate-200 text-xs uppercase text-slate-500">
          <tr>
            <th class="px-4 py-3">ID</th>
            <th class="px-4 py-3">Customer</th>
            <th class="px-4 py-3">Product</th>
            <th class="px-4 py-3 text-right">Quantity</th>
            <th class="px-4 py-3">Warehouse</th>
            <th class="px-4 py-3">Status</th>
            <th class="px-4 py-3 text-right">Order Date</th>
            <th class="px-4 py-3 text-right">Actions</th>
          </tr>
        </thead>
        <tbody>
          @for (o of getFilteredOrders(); track o.id) {
            <tr class="border-b border-slate-100 hover:bg-slate-50 transition duration-150">
              <td class="px-4 py-3 text-slate-500">#{{ o.id }}</td>
              <td class="px-4 py-3 font-semibold text-slate-900">{{ o.customer_name }}</td>
              <td class="px-4 py-3 text-slate-700">{{ o.product_name }}</td>
              <td class="px-4 py-3 text-right font-bold text-slate-900">{{ o.quantity }}</td>
              <td class="px-4 py-3 text-slate-600">
                {{ o.warehouse_name }}
                <span class="ml-1 rounded bg-violet/10 border border-violet/20 px-1.5 py-0.5 text-[10px] text-violet font-bold">
                  {{ o.warehouse_region }}
                </span>
              </td>
              <td class="px-4 py-3">
                @if (o.status === 'PENDING') {
                  <span class="rounded bg-amber/10 border border-amber/20 px-2.5 py-0.5 text-xs text-amber font-semibold tracking-wide">
                    {{ o.status }}
                  </span>
                } @else {
                  <span class="rounded bg-emerald/10 border border-emerald/20 px-2.5 py-0.5 text-xs text-emerald font-semibold tracking-wide">
                    {{ o.status }}
                  </span>
                }
              </td>
              <td class="px-4 py-3 text-right text-slate-500 text-xs font-mono">
                {{ o.created_at | date:'short' }}
              </td>
              <td class="px-4 py-3">
                <div class="flex justify-end gap-1">
                  <!-- Fulfill order button -->
                  @if (o.status === 'PENDING') {
                    <button
                      (click)="fulfillOrder(o.id!)"
                      title="Fulfill Order"
                      class="rounded-lg px-2.5 py-1 text-xs font-bold bg-emerald/10 text-emerald border border-emerald/20 hover:bg-emerald/20 transition duration-150"
                    >
                      Fulfill
                    </button>
                  }
                  <button
                    (click)="deleteOrder(o.id!)"
                    title="Cancel Order"
                    class="rounded-lg p-2 text-slate-500 hover:bg-danger/10 hover:text-danger transition duration-150"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                    </svg>
                  </button>
                </div>
              </td>
            </tr>
          }
          @if (getFilteredOrders().length === 0 && !loading) {
            <tr>
              <td colSpan="8" class="px-4 py-10 text-center text-slate-500 font-medium">
                No orders found.
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  </div>

  <!-- Loading indicator -->
  <div *ngIf="loading" class="flex items-center justify-center py-20">
    <div class="h-8 w-8 animate-spin rounded-full border-4 border-cyan/20 border-t-cyan"></div>
  </div>

  <!-- Place Order Modal Overlay -->
  <div *ngIf="modalOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
    <div class="glass w-full max-w-md rounded-3xl p-6 shadow-2xl relative">
      <h3 class="text-xl font-bold text-slate-900 mb-4">Place Customer Order</h3>
      <button (click)="modalOpen = false" class="absolute top-4 right-4 text-slate-500 hover:text-slate-950 text-xl">&times;</button>
      
      <form (submit)="saveOrder($event)" class="space-y-4">
        <div>
          <label>Customer Name</label>
          <input required placeholder="e.g. John Doe" [(ngModel)]="form.customer_name" name="customer_name" />
        </div>

        <div>
          <label>Product (Game)</label>
          <select [(ngModel)]="form.product_id" name="product_id">
            @for (p of products; track p.id) {
              <option [value]="p.id">{{ p.name }} (₹{{ p.unit_price }})</option>
            }
          </select>
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div>
            <label>Fulfill Server</label>
            <select [(ngModel)]="form.warehouse_id" name="warehouse_id">
              @for (w of warehouses; track w.id) {
                <option [value]="w.id">{{ w.name }} ({{ w.region }})</option>
              }
            </select>
          </div>
          <div>
            <label>Quantity</label>
            <input type="number" required [(ngModel)]="form.quantity" name="quantity" min="1" />
          </div>
        </div>

        <div class="flex justify-end gap-2 pt-4">
          <button
            type="button"
            (click)="modalOpen = false"
            class="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition duration-150"
          >
            Cancel
          </button>
          <button
            type="submit"
            [disabled]="saving"
            class="px-4 py-2 text-sm font-semibold bg-gradient-to-r from-cyan to-violet text-white rounded-xl shadow-glow disabled:opacity-60 transition duration-150"
          >
            {{ saving ? 'Placing…' : 'Place Order' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// frontend/src/pages/Orders.jsx
import { useEffect, useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ShoppingCart, Plus, Play, Trash2, X } from "lucide-react";
import toast from "react-hot-toast";
import client from "../api/client";
import PageHeader from "../components/ui/PageHeader";
import Modal from "../components/ui/Modal";

const COLUMNS = ["PENDING", "PROCESSING", "COMPLETED", "FAILED"];
const COL_COLOR = {
  PENDING: "border-amber/30",
  PROCESSING: "border-cyan/30",
  COMPLETED: "border-emerald/30",
  FAILED: "border-danger/30",
};

export default function Orders() {
  const [orders, setOrders] = useState([]);
  const [products, setProducts] = useState([]);
  const [warehouses, setWarehouses] = useState([]);
  const [modalOpen, setModalOpen] = useState(false);
  const [items, setItems] = useState([{ product_id: "", warehouse_id: "", quantity: 1 }]);
  const [notes, setNotes] = useState("");
  const [busy, setBusy] = useState(null);

  const load = useCallback(async () => {
    const { data } = await client.get("/orders");
    setOrders(data);
  }, []);

  useEffect(() => {
    load();
    client.get("/products").then((r) => setProducts(r.data));
    client.get("/warehouses").then((r) => setWarehouses(r.data));
  }, [load]);

  async function fulfill(id) {
    setBusy(id);
    try {
      await client.post(`/orders/${id}/fulfill`);
      toast.success("Order fulfilled — stock decremented atomically");
      load();
    } catch {
      toast.error("Fulfillment rolled back — see Transaction Log");
      load();
    } finally {
      setBusy(null);
    }
  }

  async function remove(id) {
    try {
      await client.delete(`/orders/${id}`);
      toast.success("Order deleted");
      load();
    } catch {
      /* toasted */
    }
  }

  async function createOrder(e) {
    e.preventDefault();
    const payload = {
      notes: notes || null,
      items: items
        .filter((i) => i.product_id && i.warehouse_id)
        .map((i) => ({
          product_id: parseInt(i.product_id, 10),
          warehouse_id: parseInt(i.warehouse_id, 10),
          quantity: parseInt(i.quantity, 10),
        })),
    };
    if (!payload.items.length) return toast.error("Add at least one item");
    try {
      await client.post("/orders", payload);
      toast.success("Order created");
      setModalOpen(false);
      setItems([{ product_id: "", warehouse_id: "", quantity: 1 }]);
      setNotes("");
      load();
    } catch {
      /* toasted */
    }
  }

  return (
    <div>
      <PageHeader
        title="Orders"
        subtitle="Fulfillment runs as an ACID transaction with rollback"
        icon={ShoppingCart}
        action={
          <button
            onClick={() => setModalOpen(true)}
            className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet px-4 py-2.5 text-sm font-semibold text-white shadow-glow"
          >
            <Plus size={18} /> New Order
          </button>
        }
      />

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        {COLUMNS.map((col) => {
          const colOrders = orders.filter((o) => o.status === col);
          return (
            <div key={col} className={`glass rounded-2xl border-t-2 p-4 ${COL_COLOR[col]}`}>
              <div className="mb-3 flex items-center justify-between">
                <h3 className="text-sm font-bold uppercase tracking-wide text-white">{col}</h3>
                <span className="rounded-full bg-white/10 px-2 text-xs text-slate-300">
                  {colOrders.length}
                </span>
              </div>
              <div className="flex flex-col gap-3">
                <AnimatePresence>
                  {colOrders.map((o) => (
                    <motion.div
                      key={o.id}
                      layout
                      initial={{ opacity: 0, y: 12 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 0.9 }}
                      className="rounded-xl border border-white/10 bg-white/5 p-3"
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-mono text-xs text-cyan">{o.order_number}</span>
                        <button
                          onClick={() => remove(o.id)}
                          className="text-slate-500 hover:text-danger"
                        >
                          <Trash2 size={14} />
                        </button>
                      </div>
                      <div className="mt-2 text-sm text-white">
                        ₹{Number(o.total_amount || 0).toLocaleString("en-IN")}
                      </div>
                      <div className="text-[11px] text-slate-400">
                        {o.items.length} item(s) · {new Date(o.created_at).toLocaleDateString()}
                      </div>
                      {(col === "PENDING" || col === "FAILED") && (
                        <button
                          onClick={() => fulfill(o.id)}
                          disabled={busy === o.id}
                          className="mt-3 flex w-full items-center justify-center gap-1.5 rounded-lg bg-gradient-to-r from-emerald/80 to-emerald py-1.5 text-xs font-semibold text-white disabled:opacity-50"
                        >
                          <Play size={13} /> {busy === o.id ? "Processing…" : "Fulfill"}
                        </button>
                      )}
                    </motion.div>
                  ))}
                </AnimatePresence>
                {colOrders.length === 0 && (
                  <p className="py-6 text-center text-xs text-slate-600">Empty</p>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="New Order" width="max-w-2xl">
        <form onSubmit={createOrder} className="space-y-3">
          {items.map((it, i) => (
            <div key={i} className="grid grid-cols-12 gap-2">
              <div className="col-span-5">
                {i === 0 && <label>Product</label>}
                <select
                  value={it.product_id}
                  onChange={(e) =>
                    setItems(items.map((x, j) => (j === i ? { ...x, product_id: e.target.value } : x)))
                  }
                >
                  <option value="">— product —</option>
                  {products.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name}
                    </option>
                  ))}
                </select>
              </div>
              <div className="col-span-4">
                {i === 0 && <label>Warehouse</label>}
                <select
                  value={it.warehouse_id}
                  onChange={(e) =>
                    setItems(items.map((x, j) => (j === i ? { ...x, warehouse_id: e.target.value } : x)))
                  }
                >
                  <option value="">— warehouse —</option>
                  {warehouses.map((w) => (
                    <option key={w.id} value={w.id}>
                      {w.name}
                    </option>
                  ))}
                </select>
              </div>
              <div className="col-span-2">
                {i === 0 && <label>Qty</label>}
                <input
                  type="number"
                  min="1"
                  value={it.quantity}
                  onChange={(e) =>
                    setItems(items.map((x, j) => (j === i ? { ...x, quantity: e.target.value } : x)))
                  }
                />
              </div>
              <div className="col-span-1 flex items-end">
                {items.length > 1 && (
                  <button
                    type="button"
                    onClick={() => setItems(items.filter((_, j) => j !== i))}
                    className="rounded-lg p-2 text-slate-400 hover:text-danger"
                  >
                    <X size={16} />
                  </button>
                )}
              </div>
            </div>
          ))}
          <button
            type="button"
            onClick={() => setItems([...items, { product_id: "", warehouse_id: "", quantity: 1 }])}
            className="text-xs text-cyan hover:underline"
          >
            + Add line item
          </button>
          <div>
            <label>Notes</label>
            <input value={notes} onChange={(e) => setNotes(e.target.value)} />
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={() => setModalOpen(false)}
              className="rounded-lg border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5"
            >
              Cancel
            </button>
            <button className="rounded-lg bg-gradient-to-r from-cyan to-violet px-4 py-2 text-sm font-semibold text-white">
              Create Order
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
}
