// frontend/src/app/pages/inventory/inventory.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { InventoryService, InventoryItem, BatchUpdatePayload } from '../../services/inventory.service';
import { ProductService, Product } from '../../services/product.service';
import { WarehouseService, Warehouse } from '../../services/warehouse.service';
import { ToastService } from '../../services/toast.service';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-inventory',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './inventory.component.html',
  styleUrls: ['./inventory.component.css']
})
export class InventoryComponent implements OnInit {
  inventory: InventoryItem[] = [];
  products: Product[] = [];
  warehouses: Warehouse[] = [];
  loading = true;

  // Filter States
  searchQuery = '';
  selectedRegion = 'ALL';
  regions = ['ALL', 'NORTH', 'SOUTH', 'EAST', 'WEST', 'CENTRAL'];

  // Add Inventory State
  addModalOpen = false;
  addForm = {
    product_id: 0,
    warehouse_id: 0,
    quantity: 10
  };

  // Batch Update Modal State
  batchModalOpen = false;
  batchItems: { product_id: number; warehouse_id: number; quantity: number }[] = [];
  batchSaving = false;

  // Concurrency Test Modal State
  concurrencyModalOpen = false;
  concurrencyForm = {
    product_id: 0,
    warehouse_id: 0,
    quantity: 5
  };
  concurrencyRunning = false;
  concurrencyResult: any = null;

  constructor(
    private inventoryService: InventoryService,
    private productService: ProductService,
    private warehouseService: WarehouseService,
    private toast: ToastService
  ) {}

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.loading = true;
    forkJoin({
      inventory: this.inventoryService.getInventory(),
      products: this.productService.getProducts(),
      warehouses: this.warehouseService.getWarehouses()
    }).subscribe({
      next: (res) => {
        this.inventory = res.inventory;
        this.products = res.products;
        this.warehouses = res.warehouses;
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  getFilteredInventory(): InventoryItem[] {
    let filtered = this.inventory;

    // Filter by Region
    if (this.selectedRegion !== 'ALL') {
      filtered = filtered.filter(item => item.warehouse_region === this.selectedRegion);
    }

    // Filter by Search Query
    if (this.searchQuery.trim()) {
      const q = this.searchQuery.toLowerCase();
      filtered = filtered.filter(item =>
        (item.product_name || '').toLowerCase().includes(q) ||
        (item.warehouse_name || '').toLowerCase().includes(q)
      );
    }

    return filtered;
  }

  // Single Add Inventory
  openAddModal(): void {
    if (this.products.length === 0 || this.warehouses.length === 0) {
      this.toast.error('Products and warehouses must exist first');
      return;
    }
    this.addForm = {
      product_id: this.products[0].id || 0,
      warehouse_id: this.warehouses[0].id || 0,
      quantity: 10
    };
    this.addModalOpen = true;
  }

  saveAddInventory(event: Event): void {
    event.preventDefault();
    const payload = {
      product_id: Number(this.addForm.product_id),
      warehouse_id: Number(this.addForm.warehouse_id),
      quantity: Number(this.addForm.quantity)
    };

    this.inventoryService.createInventory(payload).subscribe({
      next: () => {
        this.toast.success('Inventory record added');
        this.addModalOpen = false;
        this.loadData();
      }
    });
  }

  deleteInventory(id: number): void {
    this.inventoryService.deleteInventory(id).subscribe({
      next: () => {
        this.toast.success('Inventory row removed');
        this.loadData();
      }
    });
  }

  // Batch Update
  openBatchModal(): void {
    if (this.products.length === 0 || this.warehouses.length === 0) {
      this.toast.error('Products and warehouses must exist first');
      return;
    }
    this.batchItems = [{
      product_id: this.products[0].id || 0,
      warehouse_id: this.warehouses[0].id || 0,
      quantity: 10
    }];
    this.batchModalOpen = true;
  }

  addBatchItem(): void {
    this.batchItems.push({
      product_id: this.products[0].id || 0,
      warehouse_id: this.warehouses[0].id || 0,
      quantity: 10
    });
  }

  removeBatchItem(index: number): void {
    this.batchItems.splice(index, 1);
  }

  submitBatchUpdate(): void {
    if (this.batchItems.length === 0) return;
    this.batchSaving = true;

    const payload: BatchUpdatePayload = {
      items: this.batchItems.map(item => ({
        product_id: Number(item.product_id),
        warehouse_id: Number(item.warehouse_id),
        quantity: Number(item.quantity)
      }))
    };

    this.inventoryService.batchUpdate(payload).subscribe({
      next: (res) => {
        this.toast.success('Batch transaction completed successfully');
        this.batchModalOpen = false;
        this.loadData();
        this.batchSaving = false;
      },
      error: () => {
        this.batchSaving = false;
      }
    });
  }

  // Concurrency Test
  openConcurrencyModal(): void {
    if (this.products.length === 0 || this.warehouses.length === 0) {
      this.toast.error('Products and warehouses must exist first');
      return;
    }
    this.concurrencyForm = {
      product_id: this.products[0].id || 0,
      warehouse_id: this.warehouses[0].id || 0,
      quantity: 5
    };
    this.concurrencyResult = null;
    this.concurrencyModalOpen = true;
  }

  runConcurrencyTest(): void {
    this.concurrencyRunning = true;
    this.concurrencyResult = null;

    const payload = {
      product_id: Number(this.concurrencyForm.product_id),
      warehouse_id: Number(this.concurrencyForm.warehouse_id),
      quantity: Number(this.concurrencyForm.quantity)
    };

    this.inventoryService.runConcurrentTest(payload).subscribe({
      next: (res) => {
        this.concurrencyResult = res;
        this.concurrencyRunning = false;
        this.toast.success('Concurrency test completed');
        this.loadData();
      },
      error: (err) => {
        this.concurrencyResult = {
          success: false,
          error: err?.error?.detail || 'Transaction conflict or database error'
        };
        this.concurrencyRunning = false;
      }
    });
  }
}

<div class="animate-fadeIn">
  <!-- Page Header -->
  <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
    <div>
      <h1 class="text-2xl font-bold text-slate-900 flex items-center gap-2">
        <svg class="w-6 h-6 text-cyan" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" /></svg>
        Inventory
      </h1>
      <p class="text-sm text-slate-500">Total items across all partitions</p>
    </div>
    <div class="flex flex-wrap gap-2">
      <!-- Concurrency beaker button -->
      <button
        (click)="openConcurrencyModal()"
        title="Test Concurrency Lock"
        class="flex items-center justify-center gap-2 rounded-xl border border-violet/20 bg-violet/5 px-4 py-2.5 text-sm font-semibold text-violet hover:bg-violet/10 transition duration-300"
      >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 3.104v5.267m3.72-5.267v5.267M12.001 15v.008h-.008V15h.008Zm0-3.75v.008h-.008v-.008h.008ZM9.75 21h4.5m1.5-12.75h-7.5M9.75 3.104c-1.34.195-2.628.718-3.75 1.507V3.104c1.122-.79 2.41-1.312 3.75-1.507M14.25 3.104c1.34.195 2.628.718 3.75 1.507V3.104c-1.122-.79-2.41-1.312-3.75-1.507ZM5.12 18.599c.108.544.372 1.043.766 1.437C7.065 21.215 8.94 21.75 12 21.75s4.935-.535 6.114-1.714c.394-.394.658-.893.766-1.437l1.12-5.599c.311-1.556-.763-3.003-2.35-3.003h-11.3c-1.587 0-2.661 1.447-2.35 3.003l1.12 5.599Z" />
        </svg>
        <span>Test Concurrency</span>
      </button>

      <!-- Batch Update button -->
      <button
        (click)="openBatchModal()"
        class="flex items-center justify-center gap-2 rounded-xl border border-cyan/20 bg-cyan/5 px-4 py-2.5 text-sm font-semibold text-cyan hover:bg-cyan/10 transition duration-300"
      >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
        </svg>
        <span>Batch Update</span>
      </button>

      <!-- Add Stock button -->
      <button
        (click)="openAddModal()"
        class="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet px-4 py-2.5 text-sm font-semibold text-white shadow-glow hover:opacity-90 transition duration-300"
      >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
        </svg>
        <span>Add Stock</span>
      </button>
    </div>
  </div>

  <!-- Search & Filter Controls -->
  <div class="mb-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
    <!-- Region select pills -->
    <div class="flex gap-2">
      @for (reg of regions; track reg) {
        <button
          (click)="selectedRegion = reg"
          [ngClass]="selectedRegion === reg ? 'bg-gradient-to-r from-cyan to-violet text-white shadow-glow' : 'glass text-slate-600 hover:text-slate-900'"
          class="px-3.5 py-1.5 rounded-xl text-xs font-semibold uppercase tracking-wider transition duration-200"
        >
          {{ reg }}
        </button>
      }
    </div>

    <!-- Search input -->
    <div class="relative w-full md:max-w-xs">
      <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
      <input
        placeholder="Search inventory…"
        [(ngModel)]="searchQuery"
        class="!pl-9"
      />
    </div>
  </div>

  <!-- Inventory Table -->
  <div class="glass overflow-hidden rounded-2xl">
    <div class="overflow-x-auto">
      <table class="w-full text-left text-sm">
        <thead class="border-b border-slate-200 text-xs uppercase text-slate-500">
          <tr>
            <th class="px-4 py-3">Product Name</th>
            <th class="px-4 py-3">Warehouse</th>
            <th class="px-4 py-3">Partition</th>
            <th class="px-4 py-3 text-right">Quantity</th>
            <th class="px-4 py-3 text-right">Last Updated</th>
            <th class="px-4 py-3 text-right">Actions</th>
          </tr>
        </thead>
        <tbody>
          @for (item of getFilteredInventory(); track item.id) {
            <tr class="border-b border-slate-100 hover:bg-slate-50 transition duration-150">
              <td class="px-4 py-3">
                <div class="font-semibold text-slate-900">{{ item.product_name }}</div>
              </td>
              <td class="px-4 py-3 text-slate-700">{{ item.warehouse_name }}</td>
              <td class="px-4 py-3">
                <span class="rounded bg-violet/10 border border-violet/20 px-2 py-0.5 text-xs text-violet font-bold">
                  {{ item.warehouse_region }}
                </span>
              </td>
              <td class="px-4 py-3 text-right font-bold text-slate-900">{{ item.quantity | number }}</td>
              <td class="px-4 py-3 text-right text-slate-500 text-xs font-mono">
                {{ item.updated_at | date:'short' }}
              </td>
              <td class="px-4 py-3">
                <div class="flex justify-end">
                  <button
                    (click)="deleteInventory(item.id!)"
                    class="rounded-lg p-2 text-slate-500 hover:bg-danger/10 hover:text-danger transition duration-150"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                    </svg>
                  </button>
                </div>
              </td>
            </tr>
          }
          @if (getFilteredInventory().length === 0 && !loading) {
            <tr>
              <td colSpan="6" class="px-4 py-10 text-center text-slate-500 font-medium">
                No inventory records found.
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  </div>

  <!-- Loading indicator -->
  <div *ngIf="loading" class="flex items-center justify-center py-20">
    <div class="h-8 w-8 animate-spin rounded-full border-4 border-cyan/20 border-t-cyan"></div>
  </div>

  <!-- Add Single Stock Modal -->
  <div *ngIf="addModalOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
    <div class="glass w-full max-w-md rounded-3xl p-6 shadow-2xl relative">
      <h3 class="text-xl font-bold text-slate-900 mb-4">Add Inventory Stock</h3>
      <button (click)="addModalOpen = false" class="absolute top-4 right-4 text-slate-500 hover:text-slate-950 text-xl">&times;</button>
      
      <form (submit)="saveAddInventory($event)" class="space-y-4">
        <div>
          <label>Product (Game)</label>
          <select [(ngModel)]="addForm.product_id" name="product_id">
            @for (p of products; track p.id) {
              <option [value]="p.id">{{ p.name }} ({{ p.sku }})</option>
            }
          </select>
        </div>

        <div>
          <label>Warehouse (Server)</label>
          <select [(ngModel)]="addForm.warehouse_id" name="warehouse_id">
            @for (w of warehouses; track w.id) {
              <option [value]="w.id">{{ w.name }} ({{ w.region }})</option>
            }
          </select>
        </div>

        <div>
          <label>Stock Quantity</label>
          <input type="number" required [(ngModel)]="addForm.quantity" name="quantity" />
        </div>

        <div class="flex justify-end gap-2 pt-4">
          <button
            type="button"
            (click)="addModalOpen = false"
            class="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition duration-150"
          >
            Cancel
          </button>
          <button
            type="submit"
            class="px-4 py-2 text-sm font-semibold bg-gradient-to-r from-cyan to-violet text-white rounded-xl shadow-glow transition duration-150"
          >
            Add Stock
          </button>
        </div>
      </form>
    </div>
  </div>

  <!-- Batch Update Modal -->
  <div *ngIf="batchModalOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
    <div class="glass w-full max-w-2xl rounded-3xl p-6 shadow-2xl relative">
      <h3 class="text-xl font-bold text-slate-900 mb-2">Batch Inventory Transaction</h3>
      <p class="text-xs text-slate-500 mb-4">
        ACID Transaction: All updates are processed atomically. If one fails, the database rolls back everything.
      </p>
      <button (click)="batchModalOpen = false" class="absolute top-4 right-4 text-slate-500 hover:text-slate-950 text-xl">&times;</button>
      
      <div class="max-h-72 overflow-y-auto space-y-3 pr-2 mb-4">
        @for (item of batchItems; track $index) {
          <div class="flex gap-2 items-end bg-slate-50 p-3 rounded-xl border border-slate-200/60">
            <div class="flex-1">
              <label class="text-[10px]">Product</label>
              <select [(ngModel)]="item.product_id">
                @for (p of products; track p.id) {
                  <option [value]="p.id">{{ p.name }}</option>
                }
              </select>
            </div>
            <div class="flex-1">
              <label class="text-[10px]">Warehouse</label>
              <select [(ngModel)]="item.warehouse_id">
                @for (w of warehouses; track w.id) {
                  <option [value]="w.id">{{ w.name }} ({{ w.region }})</option>
                }
              </select>
            </div>
            <div class="w-24">
              <label class="text-[10px]">Quantity</label>
              <input type="number" [(ngModel)]="item.quantity" />
            </div>
            <button
              (click)="removeBatchItem($index)"
              [disabled]="batchItems.length <= 1"
              class="rounded-lg p-2 text-slate-500 hover:bg-danger/10 hover:text-danger disabled:opacity-30 transition"
            >
              &times;
            </button>
          </div>
        }
      </div>

      <div class="flex justify-between items-center pt-2">
        <button
          (click)="addBatchItem()"
          class="flex items-center gap-1 text-xs text-cyan font-semibold hover:underline"
        >
          + Add Item
        </button>
        <div class="flex gap-2">
          <button
            (click)="batchModalOpen = false"
            class="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition"
          >
            Cancel
          </button>
          <button
            (click)="submitBatchUpdate()"
            [disabled]="batchSaving"
            class="px-4 py-2 text-sm font-semibold bg-gradient-to-r from-cyan to-violet text-white rounded-xl shadow-glow disabled:opacity-60 transition"
          >
            {{ batchSaving ? 'Processing…' : 'Submit Transaction' }}
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Concurrency Test Modal -->
  <div *ngIf="concurrencyModalOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
    <div class="glass w-full max-w-lg rounded-3xl p-6 shadow-2xl relative">
      <h3 class="text-xl font-bold text-slate-900 mb-2 flex items-center gap-2">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-violet">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 3.104v5.267m3.72-5.267v5.267M12.001 15v.008h-.008V15h.008Zm0-3.75v.008h-.008v-.008h.008ZM9.75 21h4.5m1.5-12.75h-7.5M9.75 3.104c-1.34.195-2.628.718-3.75 1.507V3.104c1.122-.79 2.41-1.312 3.75-1.507M14.25 3.104c1.34.195 2.628.718 3.75 1.507V3.104c-1.122-.79-2.41-1.312-3.75-1.507ZM5.12 18.599c.108.544.372 1.043.766 1.437C7.065 21.215 8.94 21.75 12 21.75s4.935-.535 6.114-1.714c.394-.394.658-.893.766-1.437l1.12-5.599c.311-1.556-.763-3.003-2.35-3.003h-11.3c-1.587 0-2.661 1.447-2.35 3.003l1.12 5.599Z" />
        </svg>
        Row-Lock Concurrency Demo
      </h3>
      <p class="text-xs text-slate-500 mb-4">
        Fires two simultaneous writes to the same stock row. The database uses SELECT ... FOR UPDATE row locking to prevent write collisions and ensure correct quantity values.
      </p>
      <button (click)="concurrencyModalOpen = false" class="absolute top-4 right-4 text-slate-500 hover:text-slate-950 text-xl">&times;</button>
      
      <div class="space-y-4 mb-6">
        <div>
          <label>Product (Game)</label>
          <select [(ngModel)]="concurrencyForm.product_id">
            @for (p of products; track p.id) {
              <option [value]="p.id">{{ p.name }}</option>
            }
          </select>
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div>
            <label>Warehouse</label>
            <select [(ngModel)]="concurrencyForm.warehouse_id">
              @for (w of warehouses; track w.id) {
                <option [value]="w.id">{{ w.name }} ({{ w.region }})</option>
              }
            </select>
          </div>
          <div>
            <label>Increment Quantity</label>
            <input type="number" [(ngModel)]="concurrencyForm.quantity" />
          </div>
        </div>

        <!-- Result Box -->
        <div *ngIf="concurrencyResult" class="mt-4 p-4 rounded-xl border text-slate-700" [ngClass]="concurrencyResult.success !== false ? 'border-emerald/20 bg-emerald/5' : 'border-danger/20 bg-danger/5'">
          <div class="text-xs font-bold uppercase tracking-wider mb-2" [ngClass]="concurrencyResult.success !== false ? 'text-emerald' : 'text-danger'">
            {{ concurrencyResult.success !== false ? 'Success' : 'Conflict Prevented' }}
          </div>
          <div class="text-xs space-y-1 font-mono">
            @if (concurrencyResult.success !== false) {
              <p>Tx 1: {{ concurrencyResult.tx1?.message }}</p>
              <p>Tx 2: {{ concurrencyResult.tx2?.message }}</p>
              <p class="mt-2 text-[10px] text-slate-500">Locking successfully serialized both operations.</p>
            } @else {
              <p>Error: {{ concurrencyResult.error }}</p>
            }
          </div>
        </div>
      </div>

      <div class="flex justify-end gap-2">
        <button
          (click)="concurrencyModalOpen = false"
          class="px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 rounded-xl transition"
        >
          Close
        </button>
        <button
          (click)="runConcurrencyTest()"
          [disabled]="concurrencyRunning"
          class="px-4 py-2 text-sm font-semibold bg-gradient-to-r from-violet to-cyan text-white rounded-xl shadow-glow disabled:opacity-60 transition"
        >
          {{ concurrencyRunning ? 'Running Test…' : 'Fire Concurrent Transactions' }}
        </button>
      </div>
    </div>
  </div>
</div>

// frontend-react/src/pages/Inventory.jsx
import { useEffect, useState, useCallback, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  ClipboardList,
  Layers,
  Plus,
  Trash2,
  Zap,
  Beaker,
  X,
} from "lucide-react";
import toast from "react-hot-toast";
import client from "../api/client";
import PageHeader from "../components/ui/PageHeader";
import StatusBadge from "../components/ui/StatusBadge";
import Modal from "../components/ui/Modal";
import TransactionOverlay from "../components/modals/TransactionOverlay";
import { containerVariants, cardVariants } from "../components/ui/AnimatedCard";

const REGIONS = ["NORTH", "SOUTH", "EAST", "WEST", "CENTRAL"];

const cellColor = (status) =>
  status === "CRITICAL"
    ? "text-danger font-bold animate-pulseDot"
    : status === "WARNING"
    ? "text-amber font-semibold"
    : "text-emerald font-semibold";

export default function Inventory() {
  const [warehouses, setWarehouses] = useState([]);
  const [activeWh, setActiveWh] = useState(null);
  const [rows, setRows] = useState([]);
  const [products, setProducts] = useState([]);

  // batch drawer
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [batch, setBatch] = useState([]); // {product_id, warehouse_id, name, delta}

  // transaction overlay
  const [txOpen, setTxOpen] = useState(false);
  const [phase, setPhase] = useState("lock");
  const [txResult, setTxResult] = useState(null);
  const [txError, setTxError] = useState("");

  // add inventory modal
  const [addOpen, setAddOpen] = useState(false);
  const [addForm, setAddForm] = useState({ product_id: "", quantity: 0 });

  const loadWarehouses = useCallback(async () => {
    const { data } = await client.get("/warehouses");
    setWarehouses(data);
    if (data.length && activeWh == null) setActiveWh(data[0].id);
  }, [activeWh]);

  const loadRows = useCallback(async () => {
    if (!activeWh) return;
    const { data } = await client.get(`/inventory/${activeWh}`);
    setRows(data);
  }, [activeWh]);

  useEffect(() => {
    loadWarehouses();
    client.get("/products").then((r) => setProducts(r.data));
  }, [loadWarehouses]);
  useEffect(() => {
    loadRows();
  }, [loadRows]);

  const currentWh = useMemo(
    () => warehouses.find((w) => w.id === activeWh),
    [warehouses, activeWh]
  );

  function addToBatch(row) {
    if (batch.some((b) => b.product_id === row.product_id)) return;
    setBatch((b) => [
      ...b,
      {
        product_id: row.product_id,
        warehouse_id: row.warehouse_id,
        name: row.product_name,
        current: row.quantity,
        delta: -5,
      },
    ]);
    setDrawerOpen(true);
  }

  async function runBatch() {
    if (!batch.length) return;
    setDrawerOpen(false);
    setTxResult(null);
    setTxError("");
    setTxOpen(true);
    setPhase("lock");
    await wait(700);
    setPhase("exec");
    try {
      const { data } = await client.post("/inventory/batch-update", {
        updates: batch.map((b) => ({
          product_id: b.product_id,
          warehouse_id: b.warehouse_id,
          quantity_delta: parseInt(b.delta, 10),
        })),
      });
      await wait(600);
      setPhase("commit");
      await wait(500);
      setTxResult(data);
      setPhase("done");
      setBatch([]);
      loadRows();
    } catch (err) {
      const detail = err?.response?.data?.detail;
      setTxError(detail?.error || "Transaction failed");
      setPhase("rollback");
      loadRows();
    }
  }

  async function runConcurrentTest(row) {
    const t = toast.loading("Firing two concurrent transactions…");
    try {
      const { data } = await client.post("/inventory/demo/concurrent-test", null, {
        params: { product_id: row.product_id, warehouse_id: row.warehouse_id, delta: 3 },
      });
      toast.success(
        `Winner: TX-${data.winner}. The other waited ${
          Math.max(...data.results.map((r) => r.waited_ms))
        }ms for the lock.`,
        { id: t, duration: 6000 }
      );
      loadRows();
    } catch {
      toast.dismiss(t);
    }
  }

  async function addInventory(e) {
    e.preventDefault();
    try {
      await client.post("/inventory", {
        product_id: parseInt(addForm.product_id, 10),
        warehouse_id: activeWh,
        quantity: parseInt(addForm.quantity, 10),
      });
      toast.success("Inventory row added");
      setAddOpen(false);
      setAddForm({ product_id: "", quantity: 0 });
      loadRows();
    } catch {
      /* toasted */
    }
  }

  async function deleteRow(row) {
    try {
      await client.delete(`/inventory/${row.id}`, {
        params: { region: row.warehouse_region },
      });
      toast.success("Removed");
      loadRows();
    } catch {
      /* toasted */
    }
  }

  return (
    <div>
      <PageHeader
        title="Inventory"
        subtitle="Per-warehouse stock · partitioned by region · live ACID updates"
        icon={ClipboardList}
        action={
          <div className="flex gap-2">
            <button
              onClick={() => setAddOpen(true)}
              className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm font-semibold text-slate-200 hover:bg-white/5"
            >
              <Plus size={18} /> Add Stock Row
            </button>
            <button
              onClick={() => setDrawerOpen(true)}
              className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet px-4 py-2.5 text-sm font-semibold text-white shadow-glow"
            >
              <Layers size={18} /> Batch Update {batch.length > 0 && `(${batch.length})`}
            </button>
          </div>
        }
      />

      {/* Warehouse tabs */}
      <div className="mb-5 flex flex-wrap gap-2">
        {warehouses.map((w) => (
          <button
            key={w.id}
            onClick={() => setActiveWh(w.id)}
            className="relative rounded-xl px-4 py-2 text-sm font-medium transition"
            style={{ color: activeWh === w.id ? "#fff" : "#94a3b8" }}
          >
            {activeWh === w.id && (
              <motion.span
                layoutId="wh-pill"
                className="absolute inset-0 -z-10 rounded-xl bg-gradient-to-r from-cyan/20 to-violet/20 shadow-glow"
              />
            )}
            {w.name}
            <span className="ml-2 rounded bg-white/10 px-1.5 text-[10px]">{w.region}</span>
          </button>
        ))}
      </div>

      <div className="glass overflow-hidden rounded-2xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-white/10 text-xs uppercase text-slate-400">
              <tr>
                <th className="px-4 py-3">SKU</th>
                <th className="px-4 py-3">Product</th>
                <th className="px-4 py-3 text-right">Quantity</th>
                <th className="px-4 py-3 text-right">Threshold</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <motion.tbody variants={containerVariants} initial="hidden" animate="visible">
              {rows.map((r) => (
                <motion.tr
                  key={r.id}
                  variants={cardVariants}
                  className="border-b border-white/5 hover:bg-white/5"
                >
                  <td className="px-4 py-3 font-mono text-xs text-cyan">{r.sku}</td>
                  <td className="px-4 py-3 font-medium text-white">{r.product_name}</td>
                  <td className={`px-4 py-3 text-right ${cellColor(r.status)}`}>{r.quantity}</td>
                  <td className="px-4 py-3 text-right text-slate-400">{r.threshold}</td>
                  <td className="px-4 py-3">
                    <StatusBadge status={r.status} />
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex justify-end gap-1">
                      <button
                        onClick={() => addToBatch(r)}
                        title="Add to batch update"
                        className="rounded-lg p-2 text-slate-400 hover:bg-cyan/10 hover:text-cyan"
                      >
                        <Zap size={16} />
                      </button>
                      <button
                        onClick={() => runConcurrentTest(r)}
                        title="Run concurrency demo on this row"
                        className="rounded-lg p-2 text-slate-400 hover:bg-violet/10 hover:text-violet"
                      >
                        <Beaker size={16} />
                      </button>
                      <button
                        onClick={() => deleteRow(r)}
                        title="Delete row"
                        className="rounded-lg p-2 text-slate-400 hover:bg-danger/10 hover:text-danger"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </td>
                </motion.tr>
              ))}
              {rows.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-4 py-10 text-center text-slate-500">
                    No stock rows for this warehouse.
                  </td>
                </tr>
              )}
            </motion.tbody>
          </table>
        </div>
      </div>

      {/* Batch drawer */}
      <AnimatePresence>
        {drawerOpen && (
          <>
            <motion.div
              className="fixed inset-0 z-40 bg-black/50 backdrop-blur-sm"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setDrawerOpen(false)}
            />
            <motion.div
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ type: "spring", damping: 26, stiffness: 240 }}
              className="glass fixed right-0 top-0 z-50 flex h-screen w-full max-w-md flex-col p-6"
            >
              <div className="mb-4 flex items-center justify-between">
                <h3 className="text-lg font-bold text-white">Batch Stock Update</h3>
                <button onClick={() => setDrawerOpen(false)} className="text-slate-400 hover:text-white">
                  <X size={18} />
                </button>
              </div>
              <p className="mb-4 text-xs text-slate-400">
                Applied atomically. Any invalid line (stock &lt; 0) rolls back the whole batch.
              </p>

              <div className="flex-1 space-y-3 overflow-y-auto">
                {batch.length === 0 && (
                  <p className="text-sm text-slate-500">
                    Click the ⚡ icon on rows to stage them here.
                  </p>
                )}
                {batch.map((b, i) => (
                  <div key={b.product_id} className="rounded-xl border border-white/10 bg-white/5 p-3">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-medium text-white">{b.name}</span>
                      <button
                        onClick={() => setBatch(batch.filter((_, j) => j !== i))}
                        className="text-slate-400 hover:text-danger"
                      >
                        <X size={14} />
                      </button>
                    </div>
                    <div className="mt-2 flex items-center gap-2">
                      <span className="text-xs text-slate-400">current {b.current} →</span>
                      <input
                        type="number"
                        value={b.delta}
                        onChange={(e) =>
                          setBatch(
                            batch.map((x, j) => (j === i ? { ...x, delta: e.target.value } : x))
                          )
                        }
                        className="w-24"
                      />
                      <span className="text-xs text-slate-400">
                        = {b.current + (parseInt(b.delta, 10) || 0)}
                      </span>
                    </div>
                  </div>
                ))}
              </div>

              <button
                onClick={runBatch}
                disabled={!batch.length}
                className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan to-violet py-3 font-semibold text-white shadow-glow disabled:opacity-50"
              >
                <Zap size={18} /> Commit Transaction
              </button>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      <TransactionOverlay
        open={txOpen}
        phase={phase}
        result={txResult}
        error={txError}
        onClose={() => setTxOpen(false)}
      />

      <Modal open={addOpen} onClose={() => setAddOpen(false)} title={`Add Stock Row — ${currentWh?.name || ""}`}>
        <form onSubmit={addInventory} className="space-y-3">
          <div>
            <label>Product</label>
            <select
              required
              value={addForm.product_id}
              onChange={(e) => setAddForm({ ...addForm, product_id: e.target.value })}
            >
              <option value="">— Select product —</option>
              {products.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name} ({p.sku})
                </option>
              ))}
            </select>
          </div>
          <div>
            <label>Initial quantity</label>
            <input
              type="number"
              min="0"
              value={addForm.quantity}
              onChange={(e) => setAddForm({ ...addForm, quantity: e.target.value })}
            />
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={() => setAddOpen(false)}
              className="rounded-lg border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5"
            >
              Cancel
            </button>
            <button className="rounded-lg bg-gradient-to-r from-cyan to-violet px-4 py-2 text-sm font-semibold text-white">
              Add
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
}

function wait(ms) {
  return new Promise((r) => setTimeout(r, ms));
}
